"""add_soft_delete

Revision ID: 1c5af4d30dae
Revises: d5e6f7a8b9c0
Create Date: 2026-07-24 21:52:17.173584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5af4d30dae'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discount_codes_vendor_id'), table_name='discount_codes')
    op.drop_index(op.f('ix_force_join_channels_vendor_id'), table_name='force_join_channels')
    op.add_column('plans', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('servers', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_transactions_discount_code_id'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_discount_code_id'), 'transactions', ['discount_code_id'], unique=False)
    op.drop_column('servers', 'is_deleted')
    op.drop_column('plans', 'is_deleted')
    op.create_index(op.f('ix_force_join_channels_vendor_id'), 'force_join_channels', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_discount_codes_vendor_id'), 'discount_codes', ['vendor_id'], unique=False)
    # ### end Alembic commands ###
